services:
  db:
    image: mysql:8.0
    container_name: mysql_refresh_test
    environment:
      MYSQL_ROOT_PASSWORD: 1sC0de!
      MYSQL_DATABASE: ssafy
    volumes:
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_refresh_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - Cokkiri-refresh-Network

  backend:
    image: ohuggy/cokkiri_refresh_be
    container_name: Cokkiri-springboot_refresh_test
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - Cokkiri-refresh-Network

  frontend:   # 'frontend' 서비스 들여쓰기 수정
    image: ohuggy/cokkiri_refresh_fe
    container_name: vuejs_refresh_test
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - Cokkiri-refresh-Network

volumes:
  mysql_refresh_data:

networks:
  Cokkiri-refresh-Network:
    driver: bridge
